function love.conf(t)
  t.window.title = "Pastelizer"                 -- The window title (string)
  t.window.icon = "assets/icons/pastelizer.png" -- Filepath to an image to use as the window's icon (string)
  t.window.width = 800                          -- The window width (number)
  t.window.height = 600                         -- The window height (number)
  t.window.borderless = false                   -- Remove all border visuals from the window (boolean)
  t.window.resizable = false                    -- Let the window be user-resizable (boolean)
  t.window.fullscreentype = "desktop"           -- Choose between "desktop" fullscreen or "exclusive" fullscreen mode (string)
  t.window.vsync = 1                            -- Vertical sync mode (number)
end